// ═══════════════════════════════════════════════════════════════
// AMMARIA — The Merchant Realms Data Module v1.0
// ═══════════════════════════════════════════════════════════════
// Self-registering supplement module for DiceForge tools.
// Generated from verified canonical JSON data files.
// All data verified against Ammaria regional module (published).
// ═══════════════════════════════════════════════════════════════

(function() {
  var CF = window.CharacterForge;
  if (!CF || !CF.registerModule) { console.error('CharacterForge engine not loaded'); return; }

  CF.registerModule({
    id: 'ammaria',
    name: 'Ammaria — The Merchant Realms',
    description: 'Regional edges, hindrances, equipment, and characters from the Ammaria supplement.',
    alwaysOn: false,
    colour: '#C49A4A',

    // ── EDGES (18) ──
    edges: [
      // Combat Edges (5)
      {name:'Ammarian Halberd Guard',rank:'Novice',type:'Combat',reqs:'Fighting d6+',summary:'When wielding a halberd, polearm, or staff, enemies moving adjacent from outside Reach provoke a free Fighting attack. On Shake or wound, their action ends. One such attack per round.'},
      {name:'Caravan Guard',rank:'Novice',type:'Combat',reqs:'Fighting d6+ or Shooting d6+',summary:'+1 Notice to detect ambushes. +1 Fighting or Shooting (chosen at purchase) during the first round of any combat beginning as an ambush.'},
      {name:'Repeating Crossbow Training',rank:'Novice',type:'Combat',reqs:'Shooting d6+',summary:'Unlocks ROF 2 with repeating crossbows. +2 to Repair or Shooting rolls when clearing jams.'},
      {name:'Repeating Crossbow Mastery',rank:'Seasoned',type:'Combat',reqs:'Repeating Crossbow Training, Shooting d8+',summary:'Ignore Recoil penalty when firing a repeating crossbow at ROF 2.'},
      {name:'War Boar Rider',rank:'Seasoned',type:'Combat',reqs:'Riding d8+',summary:'+2 to Riding rolls involving war boars. Berserk control difficulty reduced by 2. Access to guild breeding stock at 400\u20A1.'},
      // Professional Edges (8)
      {name:'Appraiser',rank:'Novice',type:'Professional',reqs:'Smarts d6+, Notice d6+',summary:'+2 to Notice or Common Knowledge to detect forgeries, identify quality, or estimate fair prices.'},
      {name:'Blackmarket Broker',rank:'Novice',type:'Professional',reqs:'Common Knowledge d6+, Persuasion d6+',summary:'+2 to Common Knowledge to locate buyers or sellers for contraband, stolen property, or restricted items.'},
      {name:'Guild Journeyman',rank:'Novice',type:'Professional',reqs:'Smarts d6+ or Agility d6+, relevant trade skill d6+',summary:'+1 primary trade skill in guild structures. +1 Common Knowledge for guild matters and commercial law. Guild facilities provide lodging and credit.'},
      {name:'Guildmaster',rank:'Seasoned',type:'Professional',reqs:'Guild Journeyman, relevant trade skill d8+',summary:'+2 Persuasion invoking guild authority. Once per session: legal representation, emergency credit (500\u20A1), influential introductions, or guild intelligence.'},
      {name:'Moneylender',rank:'Seasoned',type:'Professional',reqs:'Smarts d8+, Persuasion d6+',summary:'+2 Persuasion involving debt, loans, or financial obligations. Notice roll to spot financial distress in others.'},
      {name:'Photographic Memory',rank:'Novice',type:'Professional',reqs:'Smarts d8+',summary:'+2 Smarts to recall names, faces, documents, maps, and previously encountered information.'},
      {name:'Sailor\'s Edge',rank:'Novice',type:'Professional',reqs:'Boating d6+, Athletics d4+',summary:'Ignore 1 point of unstable platform penalties. +1 Fighting aboard ships. +1 Persuasion with seafarers.'},
      {name:'Smuggler\'s Eye',rank:'Novice',type:'Professional',reqs:'Notice d6+',summary:'+2 Notice to detect hidden compartments, smuggled goods, or concealed weapons.'},
      // Social Edges (2)
      {name:'Patron',rank:'Novice',type:'Social',reqs:'\u2014',summary:'Monthly stipend of 50\u20A1, access to patron\'s social circles, occasional gifts. Must advance patron\'s interests in return.'},
      {name:'Reputation (Commerce)',rank:'Seasoned',type:'Social',reqs:'Persuasion d6+',summary:'+2 Persuasion with merchants, guild members, and anyone who values commercial success.'},
      // Magic Edges (3)
      {name:'Guild Trained',rank:'Novice',type:'Power',reqs:'Arcane Background (any), Smarts d6+',summary:'+2 arcane skill in proper workshop or laboratory. Can jury-rig workspace with Smarts roll.'},
      {name:'Commercial Caster',rank:'Novice',type:'Power',reqs:'Arcane Background (any), Persuasion d6+',summary:'+1 arcane skill for paying clients. +2 Persuasion when negotiating magical service fees.'},
      {name:'Oath-Binder',rank:'Novice',type:'Power',reqs:'Arcane Background (any), Smarts d6+',summary:'+2 arcane skill for powers that bind, compel, detect deception, or enforce agreements.'}
    ],

    // ── HINDRANCES (11 entries, 12 with Minor/Major split) ──
    hindrances: [
      {name:'Collaborator\'s Blood',type:'Minor',summary:'Family suspected of Glasryan service. -1 Persuasion with anyone who\'s heard the stories.'},
      {name:'Country-Born',type:'Minor',summary:'-2 Common Knowledge for guild politics, urban customs, city geography, social etiquettes.'},
      {name:'Dark Reputation',type:'Minor',summary:'-1 Persuasion with anyone who\'s heard the stories. Spreads further the longer you stay in one area.'},
      {name:'Former Slave',type:'Minor/Major',summary:'Minor: Manumitted. -2 Persuasion with respectable Ammarians, legal restrictions. Major: Escaped. As Minor, plus actively hunted.'},
      {name:'Gang Debt',type:'Major',summary:'Owe criminals. -2 vs their Intimidation. Spirit roll to refuse direct requests. Debt may be sold.'},
      {name:'Guild Blacklisted',type:'Major',summary:'Expelled from guild system. Cannot conduct legal trade. Must operate through shadow economy.'},
      {name:'Guild Obligations',type:'Minor',summary:'50\u20A1 annual dues, one week per month guild business, fines for neglect. Called upon at inconvenient times.'},
      {name:'Poverty-Marked',type:'Minor',summary:'-1 Persuasion with social betters. Visible marks of poverty.'},
      {name:'Soft Heart',type:'Minor',summary:'Spirit roll to ignore suffering or prioritise profit over principle.'},
      {name:'Tribute-Touched',type:'Major',summary:'-2 Persuasion vs Glasryans. Spirit roll to resist acting against Imperial interests.'},
      {name:'Unguilded',type:'Minor',summary:'-2 Persuasion in commerce with guild members. Cannot legally practise regulated trades.'}
    ],

    // ── GEAR ──
    gear: {
      ranged: [
        {name:'Repeating Crossbow',range:'15/30/60',dmg:'2d6',ap:3,rof:1,cost:600,wt:12,notes:'Magazine 6, ROF 2 with Training edge, Jam on critical failure'},
        {name:'Hand Crossbow',range:'5/10/20',dmg:'2d4',ap:0,rof:1,cost:150,wt:2,notes:'Concealable (-2 to spot)'},
        {name:'Dock Bow',range:'10/20/40',dmg:'2d6',ap:1,rof:1,cost:60,wt:4,notes:'Marine standard, shortbow'}
      ],
      melee: [
        {name:'Guild Halberd',dmg:'Str+d8',cost:100,wt:12,notes:'AP 1, Reach 1, two hands'},
        {name:'Guild Knife',dmg:'Str+d4',cost:25,wt:1,notes:'+1 Stealth to conceal'},
        {name:'Slaver\'s Club',dmg:'Str+d4',cost:15,wt:3,notes:'Non-lethal'},
        {name:'Sap',dmg:'Str+d4',cost:10,wt:1,notes:'Non-lethal, +2 Stealth to conceal'},
        {name:'Boat Hook',dmg:'Str+d6',cost:20,wt:4,notes:'Reach 1'}
      ],
      armor: [
        {name:'Padded Jacket',armor:1,cost:25,wt:4,notes:'Worn under clothing'},
        {name:'Guild Leathers',armor:2,cost:100,wt:8,notes:'Standard militia issue'},
        {name:'Sailor\'s Coat',armor:1,cost:75,wt:5,notes:'Water-resistant, -1 swimming penalty (not -2)'},
        {name:'Ammarian Breastplate',armor:4,cost:900,wt:15,notes:'-1 run penalty (not -2), +1 Intimidation'},
        {name:'Guild Champion Plate',armor:5,cost:2500,wt:25,notes:'Full plate, guild elite only'}
      ],
      shields: [
        {name:'Boarding Shield',parry:1,cost:50,wt:6,notes:'Can be used to shove (opposed Strength)'}
      ],
      general: [
        {name:'Ammarian Lockpicks',cost:100,wt:1,notes:'+1 Thievery'},
        {name:'Guild Scales',cost:25,wt:2,notes:'+1 to appraise weight and purity'},
        {name:'Strongbox',cost:50,wt:8,notes:'Lockable, Toughness 10'},
        {name:'Manacles',cost:15,wt:2,notes:'Strength roll at -2 to break free'},
        {name:'Smoke Bombs (\u00d73)',cost:30,wt:1,notes:'Concealment in Small Burst Template, 3 rounds'}
      ]
    },

    // ── CHARACTERS (20) ──
    characters: [
      {name:'Lyssa Thorne',concept:'Merchant Princess',ancestry:'Human',region:'Ammaria',tier:'Wild Card',rank:'Novice',category:'Pre-gen',product:'Ammaria',attrs:{agility:4,smarts:8,spirit:8,strength:4,vigor:6},skills:{Athletics:4,'Common Knowledge':8,Notice:8,Persuasion:10,Research:6,Stealth:4},edges:['Charismatic','Appraiser'],hindrances:['Stubborn','Obligation','Code of Honor'],powers:[],gearText:'Fine clothing, 150₡ cash',quote:'Everything negotiable has a price. Everything else? Also negotiable.',notes:'Born into the Thorne merchant dynasty, Lyssa broke her arranged betrothal and now builds her own commercial network. She refuses the slave trade and honours her word even when costly — principled stubbornness hidden behind a polished Ammarian facade.\n\nAdvancement: Add Guild Journeyman at Seasoned, followed by Connections or Rich.'},
      {name:'Captain Jorin Saltwind',concept:'Moonstar Veteran',ancestry:'Human',region:'Ammaria',tier:'Wild Card',rank:'Novice',category:'Pre-gen',product:'Ammaria',attrs:{agility:8,smarts:6,spirit:6,strength:6,vigor:6},skills:{Athletics:6,Boating:8,'Common Knowledge':6,Fighting:6,Notice:6,Persuasion:6,Shooting:6,Stealth:4},edges:['Sailor\'s Edge','Command','Caravan Guard'],hindrances:['Loyal','Cautious','Obligation'],powers:[],gearText:'Leather armour (+1), cutlass (Str+d6), repeating crossbow (2d6, AP 3, Range 15/30/60), sailor\'s kit, 50₡',quote:'The sea rewards competence. Ammaria rewards calculation. I provide both.',notes:'Twenty years commanding Consortium vessels taught Jorin that maritime profit requires seamanship and shrewd dealing. Commands the Silver Current coastal trader. Conservative in navigation, aggressive in negotiation.\n\nAdvancement: Add Natural Leader at Seasoned, then Combat Reflexes.'},
      {name:'Marus Ironhand',concept:'Guild Armourer',ancestry:'Human',region:'Ammaria',tier:'Wild Card',rank:'Novice',category:'Pre-gen',product:'Ammaria',attrs:{agility:6,smarts:8,spirit:6,strength:6,vigor:6},skills:{Athletics:4,'Common Knowledge':6,Fighting:6,Intimidation:4,Notice:6,Persuasion:4,Repair:10,Research:6,Stealth:4},edges:['Guild Journeyman','McGyver','Brawny'],hindrances:['Code of Honor','Loyal','Stubborn'],powers:[],gearText:'Leather apron (+1), Ammarian steel hammer (Str+d6, AP 1), master tools, 80₡',quote:'Quality speaks. Ammarian quality sings. My work bellows.',notes:'Master armourer from a five-generation craftsman family. Creates weapons and armour that nobles commission and warriors covet. Perfectionist who won\'t craft for evil purposes.\n\nAdvancement: Add Guildmaster at Seasoned, then Mr. Fix It.'},
      {name:'Kael "Boarheart" Thrace',concept:'War Boar Keeper',ancestry:'Human',region:'Ammaria',tier:'Wild Card',rank:'Novice',category:'Pre-gen',product:'Ammaria',attrs:{agility:6,smarts:6,spirit:8,strength:8,vigor:4},skills:{Athletics:6,'Common Knowledge':4,Fighting:8,Notice:6,Persuasion:4,Riding:8,Stealth:4,Survival:6},edges:['Beast Bond','Beast Master','Caravan Guard'],hindrances:['Loyal','Illiterate','Poverty-Marked'],powers:[],gearText:'Leather armour (+1), spear (Str+d6, Reach 1), short bow (2d6, Range 12/24/48), handler\'s tools, trained war boar companion, 40₡',quote:'People fear cavalry. People flee war boars. There\'s a difference.',notes:'Farm boy who discovered a talent for animal handling with family war boar stock. Now maintains breeding stock and trains mounts for guild cavalry. Protective of his charges.\n\nAdvancement: Add War Boar Rider at Seasoned, then Brawny.'},
      {name:'"Shadows"',concept:'Night\'s Whisper Operative',ancestry:'Human',region:'Ammaria',tier:'Wild Card',rank:'Novice',category:'Pre-gen',product:'Ammaria',attrs:{agility:10,smarts:6,spirit:6,strength:4,vigor:6},skills:{Athletics:8,'Common Knowledge':4,Fighting:4,Notice:6,Persuasion:4,Stealth:10,Thievery:10},edges:['Thief','Acrobat','Streetwise'],hindrances:['Wanted','Loyal','Cautious','Greedy'],powers:[],gearText:'Dark clothing, Ammarian lockpicks (+1 Thievery), guild knife (Str+d4), grappling hook with silk rope, smoke bombs, 60₡',quote:'The guild doesn\'t steal. We relocate assets to more appreciative owners.',notes:'Professional thief affiliated with Arr\'ath\'s premier thieves\' guild. Specialises in burglary and information theft. Strict professional standards: no unnecessary violence, no jobs attracting excessive attention, absolute loyalty to guild members.\n\nAdvancement: Add Fleet-Footed at Seasoned, then Improved Thief.'},
      {name:'Viktor "Silvertongue" Crane',concept:'Consortium Factor',ancestry:'Human',region:'Ammaria',tier:'Wild Card',rank:'Novice',category:'Pre-gen',product:'Ammaria',attrs:{agility:4,smarts:10,spirit:8,strength:4,vigor:6},skills:{Athletics:4,'Common Knowledge':8,Intimidation:4,Notice:8,Persuasion:10,Research:8,Stealth:4},edges:['Appraiser','Charismatic','Connections'],hindrances:['Arrogant','Obligation','Greedy'],powers:[],gearText:'Fine clothing, guild credentials, letters of credit, 200₡',quote:'Information is currency. I traffic in both.',notes:'Moonstar Consortium factor who gathers commercial intelligence. Charismatic manipulator who treats complex deals as intellectual puzzles. Secretly reports to Consortium leadership on Council activities.\n\nAdvancement: Add Guild Journeyman at Seasoned, then Investigator.'},
      {name:'Renna Ashveil',concept:'Debt-Slave Gladiator',ancestry:'Human',region:'Ammaria',tier:'Wild Card',rank:'Novice',category:'Pre-gen',product:'Ammaria',attrs:{agility:10,smarts:4,spirit:6,strength:8,vigor:4},skills:{Athletics:10,'Common Knowledge':4,Fighting:10,Intimidation:6,Notice:4,Persuasion:4,Stealth:4,Survival:6},edges:['Quick','Combat Reflexes','First Strike'],hindrances:['Obligation','Poverty','Vengeful'],powers:[],gearText:'Gladiatorial leathers (+1), gladius (Str+d6), net, Ammarian steel dagger (Str+d4, AP 1), 5₡ hidden savings',quote:'Five years contracted. Four hundred seventeen days remain.',notes:'Sold herself into term slavery to discharge family debts. Assigned gladiatorial training for master\'s profit. Shockingly skilled fighter who counts days toward freedom obsessively. Saves every copper toward early contract purchase.\n\nAdvancement: Add Block at Seasoned, then Caravan Guard after earning freedom.'},
      {name:'Daven Redstar',concept:'Ashmen Enforcer',ancestry:'Human',region:'Ammaria',tier:'Wild Card',rank:'Novice',category:'Pre-gen',product:'Ammaria',attrs:{agility:6,smarts:4,spirit:6,strength:10,vigor:8},skills:{Athletics:6,'Common Knowledge':4,Fighting:10,Intimidation:6,Notice:6,Persuasion:4,Shooting:4,Stealth:4},edges:['Brawny','Ammarian Halberd Guard'],hindrances:['Loyal','Mean','Wanted'],powers:[],gearText:'Guild leathers (+2), halberd (Str+d8, AP 1, Reach 1), Ammarian steel shortsword (Str+d6, AP 1), 30₡',quote:'The boss protects her interests. I am the boss\'s interests.',notes:'Former Steel Brotherhood veteran who found new employment after a dishonourable discharge. The Ashmen pay better anyway, and Kira Ironjaw doesn\'t ask questions about what happened in Aschenfeld.\n\nAdvancement: Add Brawny at Novice (with Advance), then Combat Reflexes at Seasoned.'},
      {name:'Elara Vossak',concept:'Guild Alchemist',ancestry:'Human',region:'Ammaria',tier:'Wild Card',rank:'Novice',category:'Pre-gen',product:'Ammaria',attrs:{agility:6,smarts:10,spirit:6,strength:4,vigor:6},skills:{'Common Knowledge':6,Fighting:4,Healing:6,Notice:6,Persuasion:6,Science:6,Spellcasting:10,Stealth:4},edges:['Arcane Background (Magic)','Alchemist','New Powers'],hindrances:['Curious','Cautious','Obligation'],powers:['Boost/Lower Trait','Environmental Protection','Healing','Light/Darkness','Stun'],gearText:'Alchemist\'s kit, guild seal, journeyman robes, dagger (Str+d4), 3 prepared healing draughts, 45₡',abName:'Magic',abSkill:'Spellcasting',pp:10,quote:'Forty crowns for the batch. The guild seal guarantees potency. What you do with it afterward is your business — and your conscience.',notes:'Journeyman alchemist licensed through the Apothecaries\' Guild. Runs a small shop in Mottgorte. Her official catalogue includes healing draughts and cleaning compounds. Her unofficial catalogue — available to trusted customers — is much wider.\n\nAdvancement: Add Rapid Recharge at Seasoned, then Power Points.'},
      {name:'Magister Conrad Holt',concept:'Guild Wizard',ancestry:'Human',region:'Ammaria',tier:'Wild Card',rank:'Novice',category:'Pre-gen',product:'Ammaria',attrs:{agility:6,smarts:10,spirit:6,strength:4,vigor:6},skills:{Academics:4,'Common Knowledge':6,Notice:6,Occult:6,Persuasion:6,Research:6,Spellcasting:10,Stealth:4},edges:['Arcane Background (Magic)','Wizard','New Powers'],hindrances:['Curious','Obligation','Quirk'],powers:['Detect/Conceal Arcana','Dispel','Lock/Unlock','Protection','Speak Language'],gearText:'Covenant robes, seal-ring (focus), spellbook disguised as legal codex, dagger (Str+d4), 120₡',abName:'Magic',abSkill:'Spellcasting',pp:10,quote:'The contract binds both parties equally. Sign here, here, and here. The Covenant seal makes it... enforceable.',notes:'Licensed wizard of the Covenant of Letters. Entered the Covenant because magic fascinated him. Fifteen years later, he spends his days verifying signatures and renewing wards. The work pays well. The work is mind-numbing. Lately, he\'s taken to accepting unusual contracts — authentication jobs in dangerous locations, work for clients the Covenant prefers to avoid.\n\nAdvancement: Add Rapid Recharge at Seasoned, then Soul Drain or Power Points.'},
      {name:'Sister Anneke Dreher',concept:'Hearthwarden of Mira',ancestry:'Human',region:'Ammaria',tier:'Wild Card',rank:'Novice',category:'Pre-gen',product:'Ammaria',attrs:{agility:6,smarts:6,spirit:10,strength:4,vigor:6},skills:{Athletics:4,'Common Knowledge':6,Faith:10,Fighting:4,Healing:6,Notice:6,Persuasion:8,Stealth:4},edges:['Arcane Background (Miracles)','Healer','New Powers'],hindrances:['Heroic','Soft Heart','Poverty'],powers:['Healing','Protection','Relief','Sanctuary','Speak Language'],gearText:'Simple robes, hearthkeeper\'s symbol (focus), healer\'s kit, staff (Str+d4, Parry +1, Reach 1), 8₡',abName:'Miracles',abSkill:'Faith',pp:10,quote:'The goddess asks only that we care for each other. Everything else — the politics, the tributes, the guild squabbles — is noise.',notes:'Anneke serves Mira the Hearthkeeper, conducting marriages, namedays, and funerals throughout Mottgorte\'s working-class districts. She knows every family, every feud, every tragedy. The gangs respect her. The Watch tolerates her. The guild temples dismiss her as a peasant comforter. None of them understand what she actually does.\n\nAdvancement: Add Rapid Recharge at Seasoned, then Holy Warrior or Champion.'},
      {name:'Brother Aldric Stern',concept:'Justicar of Valdros',ancestry:'Human',region:'Ammaria',tier:'Wild Card',rank:'Novice',category:'Pre-gen',product:'Ammaria',attrs:{agility:6,smarts:6,spirit:10,strength:6,vigor:4},skills:{Athletics:4,'Common Knowledge':4,Faith:8,Fighting:8,Intimidation:6,Notice:6,Persuasion:4,Research:6,Stealth:4},edges:['Arcane Background (Miracles)','Champion','New Powers'],hindrances:['Code of Honor','Stubborn','Vengeful'],powers:['Boost Trait','Deflection','Detect/Conceal Arcana','Protection','Smite'],gearText:'Justicar\'s robes over chain shirt (+2), holy symbol of Valdros (focus), Ammarian steel longsword (Str+d8, AP 1), manacles, legal codex, 35₡',abName:'Miracles',abSkill:'Faith',pp:10,quote:'The law is clear. Your interpretation of it is irrelevant.',notes:'Aldric believes absolutely in the law. Not guild law, which bends for money. Not city law, which bends for power. Divine law — the basic principles that bind the world. He\'s watched Ammaria erode those principles for profit. He enforces the law because someone must. He can\'t be bribed. He can\'t be threatened.\n\nAdvancement: Add Combat Reflexes at Seasoned, then Holy Warrior or Block.'},
      {name:'Vella Ashford',concept:'Herbalist',ancestry:'Human',region:'Ammaria',tier:'Wild Card',rank:'Novice',category:'NPC',product:'Ammaria',attrs:{agility:6,smarts:10,spirit:8,strength:4,vigor:6},skills:{Healing:10,Notice:8,Occult:6,Research:8,Survival:8},edges:['Healer','Scholar'],hindrances:[],powers:[],gearText:'Herbalist\'s kit, rare plants, grandmother\'s journal (partially coded), 40-80₡',quote:'My grandmother was tribute-taken. I remember what she taught me.',notes:'Appendix D: Allies & Contacts.\n\nHer grandmother, tribute-taken fifty years ago, somehow escaped Glasrya — bringing knowledge of plants and medicines unknown to Ammarian practitioners. Vella continues that tradition, offering remedies that work suspiciously well.\n\nCautious, knowledgeable, secretly bitter about what the tribute system took from her family. Rebel sympathiser but not active.\n\nServices: Healing (Healing roll +2, 10₡), antidotes (+2 vs. specific poison, 25₡), knockout drugs (25₡+, discretion required)\n\nHook: Someone\'s been asking about Vella\'s grandmother — what she knew, what she brought back. Glasryan interest, perhaps, or usurper recruitment.'},
      {name:'Dorgan Ironhide',concept:'War Boar Handler',ancestry:'Human',region:'Ammaria',tier:'Wild Card',rank:'Novice',category:'NPC',product:'Ammaria',attrs:{agility:6,smarts:8,spirit:10,strength:8,vigor:8},skills:{Athletics:6,Fighting:8,Intimidation:8,Notice:8,Riding:10,Survival:8},edges:['Beast Bond','Beast Master','War Boar Rider'],hindrances:[],powers:[],gearText:'Guild leathers (+2), war boar lance (Str+d8, Reach 2, AP 2 when charging), training gear, personal war boar ("Tusker")',quote:'I train war boars. I train riders. I don\'t train fools.',notes:'Appendix D: Allies & Contacts.\n\nMaster boar-handler maintaining breeding stock and training cavalry for the Guild of Iron. Knows more about war boars than anyone alive — their temperaments, weaknesses, and capabilities. Expensive, temperamental, and absolutely worth it.\n\nGruff, impatient with stupidity, surprisingly gentle with animals. Respects courage; despises cruelty.\n\nServices: War boar training (100₡, 4 weeks), advanced training (200₡, 8 weeks), boar purchase (400-600₡/day)\n\nHook: Someone\'s been poisoning war boars in the guild stables. Dorgan suspects sabotage — maybe agitators, maybe rival guild.'},
      {name:'Captain Arckhim Stormwright',concept:'Moonstar Captain',ancestry:'Human',region:'Ammaria',tier:'Wild Card',rank:'Novice',category:'NPC',product:'Ammaria',attrs:{agility:8,smarts:8,spirit:8,strength:8,vigor:8},skills:{Athletics:8,Boating:10,Fighting:8,Intimidation:6,Notice:8,Shooting:8},edges:['Sailor\'s Edge','Command','Steady Hands','Strong Willed'],hindrances:[],powers:[],gearText:'Reinforced leathers (+2), Ammarian steel cutlass (Str+d6+1, AP 1), pistol crossbow (2d4, 5/10/20), captain\'s coat, 200-400₡',quote:'The Consortium flies our flag, but my ship answers to me.',notes:'Appendix D: Allies & Contacts.\n\nIndependent-minded Moonstar captain whose vessel, the Gilded Serpent, technically serves Consortium interests but frequently takes private contracts that guild headquarters might not approve. Walks a careful line between profitable independence and outright insubordination.\n\nBold, charismatic, fiercely protective of his crew. Takes risks that sometimes pay off spectacularly.\n\nServices: Coastal passage (standard rates minus 20%), "no questions" cargo transport (triple rates), naval escort (negotiable), emergency extraction (500₡+)\n\nHook: Arckhim\'s discovered something during a routine voyage — wreckage, perhaps, or a signal from somewhere it shouldn\'t be.'},
      {name:'Aeldric Venca',concept:'Senior Factor / Guildmaster',ancestry:'Human',region:'Ammaria',tier:'Wild Card',rank:'Veteran',category:'NPC',product:'Ammaria',attrs:{agility:6,smarts:10,spirit:8,strength:4,vigor:6},skills:{'Common Knowledge':12,Intimidation:8,Notice:10,Persuasion:10,Research:8},edges:['Guildmaster','Appraiser','Rich','Connections','Strong Willed'],hindrances:[],powers:[],gearText:'Expensive clothing, guild credentials, rings worth more than most houses, private guards (4)',quote:'Guildmaster Venca will see you now. Mind your manners.',notes:'Appendix D: Allies & Contacts.\n\nSenior factor on the Serien Mercantile Council. Guided his trading house to remarkable success over three decades. His rivals have suffered an equally remarkable string of misfortunes: bankruptcies, scandals, convenient accidents, one memorable warehouse fire.\n\nUrbane, patient, speaks softly because he doesn\'t need to raise his voice. Never threatens — simply explains how things are.\n\nThe Truth: Everyone knows what Venca is. Nobody can prove it. The last merchant who tried to expose him vanished en route to the Council Chamber.\n\nHook: Venca has noticed the party. He\'s impressed by their capabilities. The meeting invitation is polite. Declining would be unwise.'},
      {name:'Lyssa Voss',concept:'Escaped Slave / Underground Railroad',ancestry:'Human',region:'Ammaria',tier:'Wild Card',rank:'Novice',category:'NPC',product:'Ammaria',attrs:{agility:8,smarts:8,spirit:10,strength:6,vigor:8},skills:{Athletics:6,Fighting:8,Notice:8,Persuasion:8,Stealth:8,Survival:8},edges:['Brave','Strong Willed','Connections'],hindrances:['Wanted','Enemy'],powers:[],gearText:'Dark clothing, guild knife (Str+d4), forged freedom papers, safe house locations (memorised), 20-50₡',quote:'I survived the pens. I survived escape. You think your problems scare me?',notes:'Appendix D: Allies & Contacts.\n\nFormer slave who escaped a tribute convoy three years ago and has spent every day since helping others do the same. Operates a clandestine network smuggling escaped slaves out of Ammaria. Rebellious to the Dragon Throne but independent — rebellious circles help when convenient, but Lyssa\'s mission comes first.\n\nIntense, driven, surprisingly compassionate. Judges people by actions, not words. Slow to trust but absolutely loyal once won.\n\nServices: Escaped slave transport (free), rebel contact introduction (trust must be earned), safe house access (emergencies only), forgery contacts (50₡)\n\nHook: One of Lyssa\'s safe houses has been compromised. Someone talked — or someone infiltrated.'},
      {name:'Brynn Goldleaf',concept:'Merchant Family Junior',ancestry:'Human',region:'Ammaria',tier:'Wild Card',rank:'Novice',category:'NPC',product:'Ammaria',attrs:{agility:6,smarts:10,spirit:8,strength:4,vigor:6},skills:{'Common Knowledge':10,Gambling:6,Notice:8,Persuasion:10,Research:6},edges:['Appraiser','Attractive','Rich','Connections'],hindrances:[],powers:[],gearText:'Fine clothing, guild credentials, letters of credit (family-backed), 100-200₡',quote:'My family\'s traded spices for six generations. I know things.',notes:'Appendix D: Allies & Contacts.\n\nJunior member of a mid-tier merchant family. Handles the "difficult" transactions her elders prefer not to acknowledge — sales to questionable buyers, purchases from dubious sources, negotiations where plausible deniability matters.\n\nCharming, calculating, genuinely enjoys the game of commerce. More ethical than she pretends — won\'t deal in slaves.\n\nServices: Trade negotiation (+2 to Persuasion, 10% fee), merchant family introduction (50₡), cargo valuation (free), market intelligence (20-50₡)\n\nHook: Brynn\'s discovered her family is involved in something beyond normal corruption — perhaps Glasryan collaboration, perhaps tribute skimming.'},
      {name:'Mikael Kohl',concept:'The Missing Factor',ancestry:'Human',region:'Ammaria',tier:'Wild Card',rank:'Novice',category:'NPC',product:'Ammaria Weekly Pack W01',attrs:{agility:4,smarts:10,spirit:8,strength:4,vigor:6},skills:{Academics:8,'Common Knowledge':10,Notice:8,Persuasion:4,Research:10},edges:['Eidetic Memory','Scholar'],hindrances:['Cautious','Loyal'],powers:[],gearText:'Nothing (prisoner)',notes:'Week 01: The Counting Quarter.\n\nElsbet\'s brother. Discovered Tribute fraud. Now he\'s a prisoner. Thirty-one, thin, ink-stained fingers even in captivity. He memorised the evidence — dates, amounts, names — because he knew they\'d search for documents.\n\nWhat He Wants: To survive. To see his sister again. To see justice done.\nHis Secret: He hasn\'t broken yet, but he\'s close. Three more days and he\'ll give them what they want.\n\nConnections: Brother of Elsbet Kohl. Discovered Varen\'s Tribute theft. Held by Brotherhood.'},
      {name:'Tallyman Oskar Venn',concept:'The Professional',ancestry:'Human',region:'Ammaria',tier:'Wild Card',rank:'Novice',category:'NPC',product:'Ammaria Weekly Pack W01',attrs:{agility:6,smarts:8,spirit:8,strength:6,vigor:6},skills:{'Common Knowledge':8,Fighting:6,Intimidation:8,Notice:8,Persuasion:8,Stealth:6},edges:[],hindrances:[],powers:[],gearText:'Neat clothes, ledger, club (Str+d4)',notes:'Week 01: The Counting Quarter.\n\nThe Brotherhood\'s most effective debt collector. Nothing personal. Thirty-four, neat clothes, ledger under arm. He explains terms clearly, offers payment plans, and apologises when violence becomes necessary. This makes him more frightening than the ones who enjoy it.\n\nWhat He Wants: To do his job well. To tithe to the Sacred Flame anonymously. To pretend that balances the books.\nHis Secret: He tithes 10% of his earnings to Aurelia\'s temples. It doesn\'t help him sleep.'}
    ]
  });
})();
