// ═══════════════════════════════════════════════════════════════
// SAVAGE WORLDS CORE RULES — Data Module v2.0
// ═══════════════════════════════════════════════════════════════
// Self-registering module for CharacterForge engine.
// Generated from verified canonical JSON data files.
// All data verified against SWADE core rulebook pp.12-173.
// ═══════════════════════════════════════════════════════════════

(function() {
  var CF = window.CharacterForge;
  if (!CF || !CF.registerModule) { console.error('CharacterForge engine not loaded'); return; }

  CF.registerModule({
    id: 'swade-core',
    name: 'Savage Worlds Core Rules',
    description: 'Core ancestries, edges, hindrances, powers, and equipment from the Savage Worlds Adventure Edition rulebook.',
    alwaysOn: true,
    colour: '#C4A44A',

    // ── SKILL DEFINITIONS ──
    skillLinks: {
      'Academics':'smarts',
      'Athletics':'agility',
      'Battle':'smarts',
      'Boating':'agility',
      'Common Knowledge':'smarts',
      'Driving':'agility',
      'Electronics':'smarts',
      'Faith':'spirit',
      'Fighting':'agility',
      'Focus':'spirit',
      'Gambling':'smarts',
      'Hacking':'smarts',
      'Healing':'smarts',
      'Intimidation':'spirit',
      'Language':'smarts',
      'Notice':'smarts',
      'Occult':'smarts',
      'Performance':'spirit',
      'Persuasion':'spirit',
      'Piloting':'agility',
      'Psionics':'smarts',
      'Repair':'smarts',
      'Research':'smarts',
      'Riding':'agility',
      'Science':'smarts',
      'Shooting':'agility',
      'Spellcasting':'smarts',
      'Stealth':'agility',
      'Survival':'spirit',
      'Taunt':'smarts',
      'Thievery':'agility',
      'Weird Science':'smarts'
    },
    coreSkills: ["Athletics", "Common Knowledge", "Notice", "Persuasion", "Stealth"],

    // ── ANCESTRIES ──
    ancestries: {
      'Human': {
        summary: 'Adaptable',
        abilities: ["Adaptable \u2014 Humans begin with a free Novice Edge of their choice (must meet all Requirements) and one additional attribute point."],
        attrBonus: 1, freeEdges: 1, pace: 6, size: 0, toughMod: 0
      },
      'Android': {
        summary: 'Construct, Outsider (Major), Pacifist (Major), Vow (Major)',
        abilities: ["Construct \u2014 +2 to recover from Shaken. Ignore one level of Wound modifiers. Does not breathe. Immune to poison and disease. Cannot heal naturally \u2014 requires Repair skill (one hour per current Wound level, no Golden Hour).", "Outsider (Major) \u2014 Subtract 2 from Persuasion rolls when interacting with anyone besides other androids. No legal rights in most areas (generally considered property).", "Pacifist (Major) \u2014 Built-in Hindrance. May not injure a sapient being, or through action or inaction allow such a being to be harmed.", "Vow (Major) \u2014 Built-in Hindrance. Designed with a particular purpose \u2014 a broad directive such as serving a corporation or political faction."],
        attrBonus: 0, freeEdges: 0, pace: 6, size: 0, toughMod: 0
      },
      'Aquarian': {
        summary: 'Aquatic, Low Light Vision, Toughness, Dependency',
        abilities: ["Aquatic \u2014 Cannot drown in water. Moves at full Pace when swimming.", "Dependency \u2014 Must immerse in water one hour out of every 24 or become automatically Fatigued each day until Incapacitated. The day after that, they perish. Each hour in water restores one level of Fatigue.", "Low Light Vision \u2014 Ignores penalties for Dim and Dark Illumination.", "Toughness \u2014 +1 Toughness."],
        attrBonus: 0, freeEdges: 0, pace: 6, size: 0, toughMod: 1
      },
      'Avion': {
        summary: 'Flight, Keen Senses, Can\'t Swim, Frail, Reduced Pace',
        abilities: ["Can't Swim \u2014 Subtract 2 from Athletics (swimming) rolls and each inch moved in water costs 3 inches of Pace.", "Flight \u2014 Fly at Pace 12 per round. Use Athletics when maneuvering.", "Frail \u2014 -1 Toughness due to hollow bones.", "Keen Senses \u2014 Begin with d6 in Notice (instead of d4). May raise Notice to d12+1.", "Reduced Pace \u2014 Walking Pace decreased by 1 and running die reduced one step."],
        attrBonus: 0, freeEdges: 0, pace: 5, size: 0, toughMod: -1, runDie: 4, startNotice: 6
      },
      'Celestial': {
        summary: 'Attribute Increase (Spirit), Flight, Healing, Ancestral Enemy (Demons/Devils), Vow (Major)',
        abilities: ["Ancestral Enemy \u2014 Those who descend from above do not easily tolerate those who crawl forth from the Abyss.", "Attribute Increase (Spirit) \u2014 Start with d6 Spirit instead of d4. Maximum Spirit d12+1.", "Faith \u2014 Start with d6 Faith instead of d4. Maximum Faith d12+1.", "Flight \u2014 Fly at Pace 12 per round. Use Athletics when maneuvering.", "Healing \u2014 May use a natural healing ability as an action. Roll Spirit: success heals one Wound on a touched target, raise heals two. Each use costs the celestial one level of Fatigue.", "Vow (Major) \u2014 Must protect humanity."],
        attrBonus: 0, freeEdges: 0, pace: 6, size: 0, toughMod: 0, startAttrs: {"spirit": 6}
      },
      'Dwarf': {
        summary: 'Low Light Vision, Tough, Reduced Pace',
        abilities: ["Low Light Vision \u2014 Ignores penalties for Dim and Dark Illumination.", "Reduced Pace \u2014 Pace decreased by 1 and running die reduced one step.", "Tough \u2014 Start with d6 Vigor instead of d4. Maximum Vigor d12+1."],
        attrBonus: 0, freeEdges: 0, pace: 5, size: 0, toughMod: 0, startAttrs: {"vigor": 6}, runDie: 4
      },
      'Elf': {
        summary: 'Agile, Low Light Vision, All Thumbs',
        abilities: ["Agile \u2014 Start with d6 Agility instead of d4. Maximum Agility d12+1.", "All Thumbs \u2014 Inherent dislike of mechanical objects. Have the All Thumbs Hindrance (-2 to use mechanical or electrical devices).", "Low Light Vision \u2014 Ignores penalties for Dim and Dark Illumination."],
        attrBonus: 0, freeEdges: 0, pace: 6, size: 0, toughMod: 0, startAttrs: {"agility": 6}
      },
      'Half-Elf': {
        summary: 'Heritage, Low Light Vision, Outsider (Minor)',
        abilities: ["Heritage \u2014 May either start with a free Novice Edge of their choice OR a d6 in Agility instead of d4 (which also increases Agility maximum to d12+1).", "Low Light Vision \u2014 Ignores penalties for Dim and Dark Illumination.", "Outsider (Minor) \u2014 Never quite comfortable in human or elven society. Subtract 2 from Persuasion rolls with all but others of their kind."],
        attrBonus: 0, freeEdges: 1, pace: 6, size: 0, toughMod: 0
      },
      'Half-Folk': {
        summary: 'Luck, Spirited, Reduced Pace, Size -1',
        abilities: ["Luck \u2014 Draw one additional Benny per game session.", "Reduced Pace \u2014 Pace decreased by 1 and running die reduced one step.", "Size -1 \u2014 Average about four feet tall. Size and Toughness reduced by 1.", "Spirited \u2014 Start with d6 Spirit instead of d4. Maximum Spirit d12+1."],
        attrBonus: 0, freeEdges: 0, pace: 5, size: -1, toughMod: -1, startAttrs: {"spirit": 6}, runDie: 4, bonusBennies: 1
      },
      'Rakashan': {
        summary: 'Agile, Bite/Claws, Low Light Vision, Bloodthirsty, Can\'t Swim',
        abilities: ["Agile \u2014 Start with d6 Agility instead of d4. Maximum Agility d12+1.", "Bite/Claws \u2014 Natural Weapons that cause Str+d4 damage.", "Bloodthirsty \u2014 Cruel to foes, rarely takes prisoners. Feel little compunction about punishing captured foes.", "Can't Swim \u2014 Subtract 2 from Athletics (swimming) rolls and each inch in water costs 3 inches of Pace.", "Low Light Vision \u2014 Ignores penalties for Dim and Dark Illumination."],
        attrBonus: 0, freeEdges: 0, pace: 6, size: 0, toughMod: 0, startAttrs: {"agility": 6}
      },
      'Saurian': {
        summary: 'Armor +2, Bite, Keen Senses, Environmental Weakness (Cold), Outsider (Minor)',
        abilities: ["Armor +2 \u2014 Thick pointed scales grant +2 Armor.", "Bite \u2014 Natural Weapon that causes Str+d4 damage.", "Environmental Weakness (Cold) \u2014 -4 to resist cold environmental effects. Suffer +4 damage from cold-based attacks.", "Keen Senses \u2014 Saurians have the Alertness Edge, granting +2 to Notice rolls.", "Outsider (Minor) \u2014 Most species distrust saurians. Subtract 2 from Persuasion rolls with all but others of their kind."],
        attrBonus: 0, freeEdges: 0, pace: 6, size: 0, toughMod: 0, naturalArmor: 2
      }
    },

    // ── EDGES ──
    edges: [
      {name:'Alertness',rank:'N',reqs:'—',cat:'Background',summary:'+2 to Notice rolls.'},
      {name:'Ambidextrous',rank:'N',reqs:'Agility d8+',cat:'Background',summary:'Ignore -2 penalty when making Trait rolls with off-hand.'},
      {name:'Arcane Background',rank:'N',reqs:'—',cat:'Background',summary:'Allows access to Arcane Backgrounds (Magic, Miracles, Psionics, Weird Science, Gifted).'},
      {name:'Arcane Resistance',rank:'N',reqs:'Spirit d8+',cat:'Background',summary:'Enemy arcane skills targeting the hero suffer -2; magical damage reduced by 2.'},
      {name:'Improved Arcane Resistance',rank:'N',reqs:'Arcane Resistance',cat:'Background',summary:'As Arcane Resistance but penalty increased to -4 and damage reduced by 4.'},
      {name:'Aristocrat',rank:'N',reqs:'—',cat:'Background',summary:'+2 to Common Knowledge and networking with the upper class.'},
      {name:'Attractive',rank:'N',reqs:'Vigor d6+',cat:'Background',summary:'+1 to Performance and Persuasion rolls.'},
      {name:'Very Attractive',rank:'N',reqs:'Attractive',cat:'Background',summary:'+2 to Performance and Persuasion rolls.'},
      {name:'Berserk',rank:'N',reqs:'—',cat:'Background',summary:'After being Shaken or Wounded, melee attacks must be Wild Attacks, +1 die type to Strength, +2 to Toughness, ignore one level of Wound penalties. Critical Failure on Fighting roll hits random target. Fatigue after every five consecutive rounds; may end rage with Smarts roll at -2.'},
      {name:'Brave',rank:'N',reqs:'Spirit d6+',cat:'Background',summary:'+2 to Fear checks and -2 to rolls on the Fear Table.'},
      {name:'Brawny',rank:'N',reqs:'Strength d6+, Vigor d6+',cat:'Background',summary:'Size (and Toughness) +1. Treat Strength as one die type higher for Encumbrance and Minimum Strength.'},
      {name:'Brute',rank:'N',reqs:'Strength d6+, Vigor d6+',cat:'Background',summary:'Link Athletics to Strength instead of Agility (including resistance). Short Range of thrown items increased by +1.'},
      {name:'Calculating',rank:'N',reqs:'Smarts d8+',cat:'Background',summary:'Ignore up to 2 points of situational penalties on any Trait roll.'},
      {name:'Charismatic',rank:'N',reqs:'Spirit d8+',cat:'Background',summary:'Free reroll on Persuasion rolls.'},
      {name:'Elan',rank:'N',reqs:'Spirit d8+',cat:'Background',summary:'+2 when spending a Benny to reroll a Trait roll.'},
      {name:'Fame',rank:'N',reqs:'—',cat:'Background',summary:'+1 to Persuasion rolls when recognized (usually Common Knowledge). 5x starting funds.'},
      {name:'Famous',rank:'S',reqs:'Fame',cat:'Background',summary:'+2 to Persuasion when recognized. 10x starting funds.'},
      {name:'Fast Healer',rank:'N',reqs:'Vigor d8+',cat:'Background',summary:'+2 to natural healing rolls.'},
      {name:'Fleet-Footed',rank:'N',reqs:'Agility d6+',cat:'Background',summary:'Pace +2, running die increased one step.'},
      {name:'Linguist',rank:'N',reqs:'Smarts d6+',cat:'Background',summary:'Character has d6 in Language for number of pointed equal to half Smarts die. May make Smarts roll to understand languages not pointed.'},
      {name:'Luck',rank:'N',reqs:'—',cat:'Background',summary:'+1 Benny per session.'},
      {name:'Great Luck',rank:'N',reqs:'Luck',cat:'Background',summary:'+2 Bennies per session.'},
      {name:'Quick',rank:'N',reqs:'Agility d8+',cat:'Background',summary:'Redraw Action Cards of 5 or lower.'},
      {name:'Rich',rank:'N',reqs:'—',cat:'Background',summary:'3x starting funds and a regular income.'},
      {name:'Filthy Rich',rank:'N',reqs:'Rich',cat:'Background',summary:'5x starting funds and a large income.'},
      {name:'Block',rank:'S',reqs:'Fighting d8+',cat:'Combat',summary:'+1 Parry.'},
      {name:'Improved Block',rank:'V',reqs:'Block',cat:'Combat',summary:'+2 Parry.'},
      {name:'Brawler',rank:'N',reqs:'Strength d8+, Vigor d8+',cat:'Combat',summary:'Toughness +1, add d4 to unarmed Fighting damage.'},
      {name:'Bruiser',rank:'S',reqs:'Brawler',cat:'Combat',summary:'Unarmed Fighting damage bonus is now d6. Toughness +1.'},
      {name:'Combat Reflexes',rank:'S',reqs:'—',cat:'Combat',summary:'+2 to recover from Shaken or Stunned.'},
      {name:'Counterattack',rank:'S',reqs:'Fighting d8+',cat:'Combat',summary:'Free Fighting attack against one foe per round who failed a Fighting attack against you at -2.'},
      {name:'Improved Counterattack',rank:'V',reqs:'Counterattack',cat:'Combat',summary:'Counterattack at no penalty.'},
      {name:'Dead Shot',rank:'N',reqs:'Athletics d8+',cat:'Combat',summary:'On a Joker, double total damage from first Athletics (throwing) or Shooting roll this round.'},
      {name:'Dodge',rank:'S',reqs:'Agility d8+',cat:'Combat',summary:'-2 to be hit by ranged attacks.'},
      {name:'Improved Dodge',rank:'S',reqs:'Dodge',cat:'Combat',summary:'+2 to Evasion attempts.'},
      {name:'Double Tap',rank:'S',reqs:'Shooting d6+',cat:'Combat',summary:'+1 to hit and damage when firing no more than RoF 1 with a pointed weapon.'},
      {name:'Extraction',rank:'N',reqs:'Agility d8+',cat:'Combat',summary:'One adjacent foe doesn\'t get a free attack when you withdraw from melee.'},
      {name:'Improved Extraction',rank:'S',reqs:'Extraction',cat:'Combat',summary:'Three adjacent foes don\'t get free attacks when you withdraw.'},
      {name:'Feint',rank:'N',reqs:'Fighting d8+',cat:'Combat',summary:'Make opposed Fighting roll vs. opponent\'s Smarts instead of Agility for a Test.'},
      {name:'First Strike',rank:'N',reqs:'Agility d8+',cat:'Combat',summary:'Free Fighting attack against one foe per round who moves into Reach.'},
      {name:'Improved First Strike',rank:'H',reqs:'First Strike',cat:'Combat',summary:'Free Fighting attack against every foe who moves into Reach.'},
      {name:'Free Runner',rank:'N',reqs:'Agility d8+, Athletics d6+',cat:'Combat',summary:'Ignore Difficult Ground and 2 points of penalties for climbing. +2 to Athletics in foot chases.'},
      {name:'Frenzy',rank:'S',reqs:'Fighting d8+',cat:'Combat',summary:'One extra Fighting roll with a melee weapon at no Multi-Action penalty.'},
      {name:'Improved Frenzy',rank:'V',reqs:'Frenzy',cat:'Combat',summary:'Two extra Fighting rolls with a melee weapon at no Multi-Action penalty.'},
      {name:'Giant Killer',rank:'V',reqs:'—',cat:'Combat',summary:'+1d6 damage vs. creatures three Sizes larger or more.'},
      {name:'Improvisational Fighter',rank:'S',reqs:'Smarts d6+',cat:'Combat',summary:'Ignore -2 penalty when attacking with improvised weapons.'},
      {name:'Iron Jaw',rank:'N',reqs:'Vigor d8+',cat:'Combat',summary:'+2 to Soak and Vigor rolls to avoid Knockout Blows.'},
      {name:'Killer Instinct',rank:'S',reqs:'—',cat:'Combat',summary:'Free reroll in any opposed Test the hero initiates.'},
      {name:'Hard to Kill',rank:'N',reqs:'Spirit d8+',cat:'Combat',summary:'Ignore Wound penalties when making Vigor rolls to avoid Bleeding Out.'},
      {name:'Harder to Kill',rank:'V',reqs:'Hard to Kill',cat:'Combat',summary:'50% chance of surviving \'death\' with a permanent injury.'},
      {name:'Imp. Level Headed',rank:'S',reqs:'Level Headed',cat:'Combat',summary:'Draw three Action Cards and keep the best.'},
      {name:'Level Headed',rank:'S',reqs:'Smarts d8+',cat:'Combat',summary:'Draw two Action Cards and keep the best.'},
      {name:'Marksman',rank:'S',reqs:'Athletics d8+',cat:'Combat',summary:'Ignore up to 2 points of penalties when not moving with Athletics (throwing) or Shooting. Limited action.'},
      {name:'Martial Artist',rank:'N',reqs:'Fighting d6+',cat:'Combat',summary:'Unarmed Fighting +1, fists and feet count as Natural Weapons, +d4 damage die.'},
      {name:'Martial Warrior',rank:'S',reqs:'Martial Artist',cat:'Combat',summary:'Unarmed Fighting +2, damage die is d6.'},
      {name:'Mighty Blow',rank:'N',reqs:'Fighting d8+',cat:'Combat',summary:'On a Joker, double total damage from first Fighting attack this round.'},
      {name:'Nerves of Steel',rank:'N',reqs:'Vigor d8+',cat:'Combat',summary:'Ignore one level of Wound penalties.'},
      {name:'Improved Nerves of Steel',rank:'N',reqs:'Nerves of Steel',cat:'Combat',summary:'Ignore up to two levels of Wound penalties.'},
      {name:'No Mercy',rank:'S',reqs:'—',cat:'Combat',summary:'+2 damage when spending a Benny to reroll damage.'},
      {name:'Rapid Fire',rank:'S',reqs:'Shooting d6+',cat:'Combat',summary:'Increase RoF by 1 for one Shooting attack per turn.'},
      {name:'Improved Rapid Fire',rank:'V',reqs:'Rapid Fire',cat:'Combat',summary:'Increase RoF by 1 for up to two Shooting attacks per turn.'},
      {name:'Rock and Roll!',rank:'S',reqs:'Shooting d8+',cat:'Combat',summary:'Ignore Recoil penalty when firing weapons with RoF 2+. Character may not move.'},
      {name:'Steady Hands',rank:'N',reqs:'Agility d8+',cat:'Combat',summary:'Ignore Unstable Platform penalty; reduce running penalty to -1.'},
      {name:'Sweep',rank:'N',reqs:'Strength d8+, Fighting d8+',cat:'Combat',summary:'Fighting roll with two-handed weapon (-2 without) to hit all targets in weapon\'s Reach. Limited action.'},
      {name:'Improved Sweep',rank:'V',reqs:'Sweep',cat:'Combat',summary:'As Sweep but attack can avoid allies. Limited action.'},
      {name:'Trademark Weapon',rank:'N',reqs:'d8 in related skill (Fighting, Shooting, or Athletics)',cat:'Combat',summary:'+1 to Athletics (throwing), Fighting, or Shooting total with a specific weapon; +1 Parry while weapon is readied.'},
      {name:'Imp. Trademark Weapon',rank:'S',reqs:'Trademark Weapon',cat:'Combat',summary:'Attack and Parry bonus increases to +2.'},
      {name:'Two-Fisted',rank:'N',reqs:'Agility d8+',cat:'Combat',summary:'Make one extra Fighting roll with a second melee weapon in the off-hand at no Multi-Action penalty.'},
      {name:'Two-Gun Kid',rank:'N',reqs:'Agility d8+',cat:'Combat',summary:'Make one extra Shooting (or Athletics throwing) roll with a second ranged weapon in the off-hand at no Multi-Action penalty.'},
      {name:'Command',rank:'N',reqs:'Smarts d6+',cat:'Leadership',summary:'+1 to Extras\' Shaken or Stunned recovery rolls in Command Range (5 inches / 10 yards).'},
      {name:'Command Presence',rank:'S',reqs:'Command',cat:'Leadership',summary:'Increase Command Range to 10 inches (20 yards).'},
      {name:'Fervor',rank:'V',reqs:'Spirit d8+, Command',cat:'Leadership',summary:'Extras in Command Range add +1 to their Fighting damage rolls.'},
      {name:'Hold the Line',rank:'S',reqs:'Smarts d8+, Command',cat:'Leadership',summary:'+1 to Extras\' Toughness in Command Range.'},
      {name:'Inspire',rank:'S',reqs:'Command',cat:'Leadership',summary:'Make a Battle skill roll to Support one type of Trait roll, and apply it to Extras in Command Range. Limited action.'},
      {name:'Natural Leader',rank:'S',reqs:'Spirit d8+, Command',cat:'Leadership',summary:'Leadership Edges now apply to Wild Cards as well as Extras.'},
      {name:'Tactician',rank:'S',reqs:'Smarts d8+, Battle d6+, Command',cat:'Leadership',summary:'Draw an extra Action Card each turn that may be assigned to any allied Extra in Command Range.'},
      {name:'Master Tactician',rank:'V',reqs:'Tactician',cat:'Leadership',summary:'Draw and distribute two extra Action Cards instead of one.'},
      {name:'Artificer',rank:'S',reqs:'Arcane Background',cat:'Power',summary:'Allows user to create Arcane Devices.'},
      {name:'Channeling',rank:'S',reqs:'Arcane Background',cat:'Power',summary:'Reduce Power Point cost by 1 with a raise on the arcane skill roll (can take it to 0).'},
      {name:'Concentration',rank:'S',reqs:'Arcane Background',cat:'Power',summary:'Double base Duration of non-Instant powers (including maintenance).'},
      {name:'Extra Effort',rank:'S',reqs:'Focus d6+, Arcane Background, AB (Gifted) only',cat:'Power',summary:'Increase Focus total after rolling by +1 for 1 PP, or +2 for 3 PP. Cannot improve Critical Failure.'},
      {name:'Gadgeteer',rank:'S',reqs:'Weird Science d6+, Arcane Background, AB (Weird Science) only',cat:'Power',summary:'Spend up to 3 PP to jury-rig a device replicating any power available to Weird Scientists of your Rank or lower with PP cost of 3 or less.'},
      {name:'Holy/Unholy Warrior',rank:'S',reqs:'Faith d6+, Arcane Background, AB (Miracles) only',cat:'Power',summary:'Add +1 to +4 to Soak rolls for each Power Point spent.'},
      {name:'Mentalist',rank:'S',reqs:'Psionics d6+, Arcane Background, AB (Psionics) only',cat:'Power',summary:'+2 to opposed Psionics rolls.'},
      {name:'New Powers',rank:'N',reqs:'Arcane Background',cat:'Power',summary:'Learn two new powers of your Rank or lower. May be taken multiple times.'},
      {name:'Power Points',rank:'N',reqs:'Arcane Background',cat:'Power',summary:'Gain 5 additional Power Points. May be taken once per Rank (each grants only 2 PP at Legendary).'},
      {name:'Power Surge',rank:'N',reqs:'Arcane Background, Wild Card only, arcane skill d8+',cat:'Power',summary:'Recover 10 Power Points when dealt a Joker in combat (cannot exceed usual limit).'},
      {name:'Rapid Recharge',rank:'S',reqs:'Spirit d6+, Arcane Background',cat:'Power',summary:'Recover 10 Power Points per hour (instead of 5).'},
      {name:'Improved Rapid Recharge',rank:'V',reqs:'Rapid Recharge',cat:'Power',summary:'Recover 20 Power Points per hour.'},
      {name:'Soul Drain',rank:'S',reqs:'Arcane Background, arcane skill d10+',cat:'Power',summary:'Take a level of Fatigue to recover up to 5 PP. Can take a second level (to Exhaustion) for 5 more. Cannot Incapacitate self. Fatigue recovers naturally only.'},
      {name:'Wizard',rank:'S',reqs:'Spellcasting d6+, Arcane Background, AB (Magic) only',cat:'Power',summary:'Spend 1 extra PP to change a power\'s Trapping when casting.'},
      {name:'Ace',rank:'N',reqs:'Agility d8+',cat:'Professional',summary:'May spend Bennies to Soak damage for vehicle. Ignore up to 2 points of penalties.'},
      {name:'Acrobat',rank:'N',reqs:'Agility d8+, Athletics d8+',cat:'Professional',summary:'Free reroll on acrobatic Athletics attempts.'},
      {name:'Combat Acrobat',rank:'S',reqs:'Acrobat',cat:'Professional',summary:'-1 to be hit by ranged and melee attacks.'},
      {name:'Assassin',rank:'N',reqs:'Agility d8+, Fighting d6+, Stealth d8+',cat:'Professional',summary:'+2 to damage foes when they are Vulnerable or assassin has The Drop.'},
      {name:'Investigator',rank:'N',reqs:'Smarts d8+, Research d8+',cat:'Professional',summary:'+2 to Research and certain types of Notice rolls.'},
      {name:'Jack-of-all-Trades',rank:'N',reqs:'Smarts d10+',cat:'Professional',summary:'Gain d4 in a skill (or d6 with a raise) until replaced.'},
      {name:'McGyver',rank:'N',reqs:'Smarts d6+, Repair d6+, Notice d8+',cat:'Professional',summary:'Quickly create improvised devices from scraps.'},
      {name:'Mr. Fix It',rank:'N',reqs:'Repair d8+',cat:'Professional',summary:'+2 to Repair rolls, half the time required with a raise.'},
      {name:'Scholar',rank:'N',reqs:'Research d8+',cat:'Professional',summary:'+2 to any one knowledge-type skill (Academics, Battle, Occult, Science, or GM-approved). May be taken multiple times for different skills.'},
      {name:'Soldier',rank:'N',reqs:'Strength d6+, Vigor d6+',cat:'Professional',summary:'Strength is one die type higher for Encumbrance and Min Str. Free reroll on Vigor rolls to resist environmental Hazards.'},
      {name:'Thief',rank:'N',reqs:'Agility d8+, Stealth d6+, Thievery d6+',cat:'Professional',summary:'+1 to Thievery, Athletics rolls made to climb in urban areas, and Stealth in urban environments.'},
      {name:'Woodsman',rank:'N',reqs:'Spirit d6+, Survival d8+',cat:'Professional',summary:'+2 to Survival and Stealth in the wilds.'},
      {name:'Bolster',rank:'N',reqs:'Spirit d8+',cat:'Social',summary:'May remove Distracted or Vulnerable state from an ally after a successful Test.'},
      {name:'Common Bond',rank:'N',reqs:'Spirit d8+, Wild Card only',cat:'Social',summary:'May freely give Bennies to any other character she can communicate with.'},
      {name:'Connections',rank:'N',reqs:'—',cat:'Social',summary:'Contacts provide aid or other favors once per session.'},
      {name:'Humiliate',rank:'N',reqs:'Taunt d8+',cat:'Social',summary:'Free reroll when making Taunt rolls.'},
      {name:'Menacing',rank:'N',reqs:'See text — requires a pointed appearance or deformity',cat:'Social',summary:'+2 to Intimidation.'},
      {name:'Provoke',rank:'N',reqs:'Taunt d6+',cat:'Social',summary:'With a raise on a Taunt roll, the foe must attack the taunter.'},
      {name:'Rabble-Rouser',rank:'S',reqs:'Spirit d8+',cat:'Social',summary:'Affect all foes in a Medium Blast Template with an Intimidation or Taunt Test. Limited action.'},
      {name:'Reliable',rank:'N',reqs:'Spirit d8+',cat:'Social',summary:'Free reroll when making Support rolls.'},
      {name:'Retort',rank:'N',reqs:'Taunt d6+',cat:'Social',summary:'A raise when resisting a Taunt or Intimidation attack makes the foe Distracted.'},
      {name:'Streetwise',rank:'N',reqs:'Smarts d6+',cat:'Social',summary:'+2 to Common Knowledge and criminal networking.'},
      {name:'Strong Willed',rank:'N',reqs:'Spirit d8+',cat:'Social',summary:'+2 to resist Smarts or Spirit-based Tests.'},
      {name:'Iron Will',rank:'S',reqs:'Brave, Strong Willed',cat:'Social',summary:'The bonus now applies to resisting and recovery from powers.'},
      {name:'Work the Room',rank:'N',reqs:'Spirit d8+',cat:'Social',summary:'Roll a second die when Supporting via Performance or Persuasion and apply result to additional ally. Limited action.'},
      {name:'Work the Crowd',rank:'S',reqs:'Work the Room',cat:'Social',summary:'As above, but roll a third die for a third ally. Limited action.'},
      {name:'Beast Bond',rank:'N',reqs:'—',cat:'Weird',summary:'May spend Bennies for animals under her control.'},
      {name:'Beast Master',rank:'N',reqs:'Spirit d8+',cat:'Weird',summary:'Animals like the hero and he has a pet of some sort.'},
      {name:'Champion',rank:'N',reqs:'Spirit d8+, Fighting d6+',cat:'Weird',summary:'+2 damage vs. supernaturally evil creatures.'},
      {name:'Chi',rank:'V',reqs:'Martial Warrior',cat:'Weird',summary:'Once per combat: reroll a failed attack, make an enemy reroll a successful attack, or add +d6 to unarmed Fighting attack.'},
      {name:'Danger Sense',rank:'N',reqs:'—',cat:'Weird',summary:'Notice roll at +2 to sense ambushes or similar events.'},
      {name:'Healer',rank:'N',reqs:'Spirit d8+',cat:'Weird',summary:'+2 to Healing rolls, magical or otherwise.'},
      {name:'Liquid Courage',rank:'N',reqs:'Vigor d8+',cat:'Weird',summary:'Alcohol increases Vigor one die type, ignore one level of Wound penalty; -1 to Agility, Smarts, and related skills.'},
      {name:'Scavenger',rank:'N',reqs:'Luck',cat:'Weird',summary:'May find a needed item once per encounter.'},
      {name:'Followers',rank:'L',reqs:'Wild Card only',cat:'Legendary',summary:'The hero has five followers.'},
      {name:'Professional',rank:'L',reqs:'Trait at maximum',cat:'Legendary',summary:'The character\'s Trait and its limit increases one step.'},
      {name:'Expert',rank:'L',reqs:'Professional',cat:'Legendary',summary:'The character\'s Trait and its limit increases one step.'},
      {name:'Master',rank:'L',reqs:'Expert, Wild Card only',cat:'Legendary',summary:'The character\'s Wild Die is a d10 with a chosen Trait.'},
      {name:'Sidekick',rank:'L',reqs:'Wild Card only',cat:'Legendary',summary:'The character gains a Wild Card sidekick.'},
      {name:'Tough as Nails',rank:'L',reqs:'Vigor d8+',cat:'Legendary',summary:'The hero can take four Wounds before being Incapacitated.'},
      {name:'Tougher than Nails',rank:'L',reqs:'Vigor d12+, Tough as Nails',cat:'Legendary',summary:'The hero can take five Wounds before being Incapacitated.'},
      {name:'Weapon Master',rank:'L',reqs:'Fighting d12+',cat:'Legendary',summary:'Parry +1 and Fighting bonus damage die is d8.'},
      {name:'Master of Arms',rank:'L',reqs:'Weapon Master',cat:'Legendary',summary:'Parry increases another +1 and Fighting bonus damage die is d10.'}
    ],

    // ── HINDRANCES ──
    hindrances: [
      {name:'All Thumbs',sev:'Minor',summary:'-2 to use mechanical or electrical devices.'},
      {name:'Anemic',sev:'Minor',summary:'-2 Vigor when resisting Fatigue.'},
      {name:'Arrogant',sev:'Major',summary:'Likes to dominate opponents, challenges the most powerful foe in combat.'},
      {name:'Bad Eyes',sev:'Minor/Major',summary:'-1 to all Trait rolls dependent on vision (Minor), or -2 (Major). Eyewear negates but 50% chance of breaking on trauma.'},
      {name:'Bad Luck',sev:'Major',summary:'One less Benny per session.'},
      {name:'Big Mouth',sev:'Minor',summary:'Unable to keep secrets, constantly gives away private information.'},
      {name:'Blind',sev:'Major',summary:'-6 to all tasks requiring vision. Gain choice of a free Edge to compensate.'},
      {name:'Bloodthirsty',sev:'Major',summary:'Never takes prisoners.'},
      {name:'Can\'t Swim',sev:'Minor',summary:'-2 to Athletics (swimming) rolls. Each inch moved in water costs 3 inches of Pace.'},
      {name:'Cautious',sev:'Minor',summary:'Plans extensively and/or is overly careful.'},
      {name:'Clueless',sev:'Major',summary:'-1 to Common Knowledge and Notice rolls.'},
      {name:'Clumsy',sev:'Major',summary:'-2 to Athletics and Stealth rolls.'},
      {name:'Code of Honor',sev:'Major',summary:'Keeps his word and acts like a gentleman.'},
      {name:'Curious',sev:'Major',summary:'Wants to know about everything.'},
      {name:'Death Wish',sev:'Minor',summary:'Wants to die after or while completing some epic task.'},
      {name:'Delusional',sev:'Minor/Major',summary:'Believes something strange that causes occasional (Minor) or frequent (Major) trouble.'},
      {name:'Doubting Thomas',sev:'Minor',summary:'Doesn\'t believe in the supernatural, often exposing him to unnecessary risks.'},
      {name:'Driven',sev:'Minor/Major',summary:'Actions driven by some important goal or belief.'},
      {name:'Elderly',sev:'Major',summary:'-1 to Pace, running, Agility, Strength, and Vigor. Gets 5 extra skill points.'},
      {name:'Enemy',sev:'Minor/Major',summary:'Has a recurring nemesis.'},
      {name:'Greedy',sev:'Minor/Major',summary:'Obsessed with wealth and material possessions.'},
      {name:'Habit',sev:'Minor/Major',summary:'Addicted to something. Suffers Fatigue if deprived (Major requires Vigor roll every 24 hours).'},
      {name:'Hard of Hearing',sev:'Minor/Major',summary:'-4 to Notice rolls to hear (Minor). Completely deaf and auto-fails hearing Notice (Major).'},
      {name:'Heroic',sev:'Major',summary:'Always helps those in need.'},
      {name:'Hesitant',sev:'Minor',summary:'Draw two Action Cards and act on the lowest (except Jokers, which may be kept).'},
      {name:'Illiterate',sev:'Minor',summary:'Cannot read or write in any language.'},
      {name:'Impulsive',sev:'Major',summary:'Leaps before he looks, rarely thinks things through.'},
      {name:'Jealous',sev:'Minor/Major',summary:'Covets what others have. Focused on one subject (Minor) or everyone (Major).'},
      {name:'Loyal',sev:'Minor',summary:'Loyal to friends and allies, risks life for them without hesitation.'},
      {name:'Mean',sev:'Minor',summary:'-1 to Persuasion rolls.'},
      {name:'Mild Mannered',sev:'Minor',summary:'-2 to Intimidation rolls.'},
      {name:'Mute',sev:'Major',summary:'Cannot speak. Must use written messages, sign language, or visual communication.'},
      {name:'Obese',sev:'Minor',summary:'Size +1, Pace -1, running die reduced one step. Treat Strength as one die lower for Min Str of armour/gear.'},
      {name:'Obligation',sev:'Minor/Major',summary:'Has a regular responsibility consuming ~20 hours/week (Minor) or 40+ (Major).'},
      {name:'One Arm',sev:'Major',summary:'-4 to tasks requiring two hands (some Athletics rolls, two-handed weapons).'},
      {name:'One Eye',sev:'Major',summary:'-2 to actions at 5 inches (10 yards) or more distance.'},
      {name:'Outsider',sev:'Minor/Major',summary:'-2 to Persuasion. As Major, has no legal rights or other serious consequences.'},
      {name:'Overconfident',sev:'Major',summary:'Believes she can do anything.'},
      {name:'Pacifist',sev:'Minor/Major',summary:'Fights only in self-defence (Minor). Won\'t fight at all (Major).'},
      {name:'Phobia',sev:'Minor/Major',summary:'-1 (Minor) or -2 (Major) to all Trait rolls in the presence of the feared thing.'},
      {name:'Poverty',sev:'Minor',summary:'Half starting funds and always broke.'},
      {name:'Quirk',sev:'Minor',summary:'Some minor but persistent foible that often annoys others.'},
      {name:'Ruthless',sev:'Minor/Major',summary:'Does what it takes to get her way.'},
      {name:'Secret',sev:'Minor/Major',summary:'Has a dark secret of some kind.'},
      {name:'Shamed',sev:'Minor/Major',summary:'Haunted by some tragic event from the past.'},
      {name:'Slow',sev:'Minor/Major',summary:'Pace -1, running die reduced one step (Minor). Pace -2, -2 to Athletics and rolls to resist Athletics (Major). Cannot take Fleet-Footed.'},
      {name:'Small',sev:'Minor',summary:'Size and Toughness reduced by 1. Size cannot go below -1.'},
      {name:'Stubborn',sev:'Minor',summary:'Wants his way, rarely admits mistakes.'},
      {name:'Suspicious',sev:'Minor/Major',summary:'Paranoid. As Major, allies subtract 2 when rolling to Support him.'},
      {name:'Thin Skinned',sev:'Minor/Major',summary:'-2 when resisting Taunt (Minor) or -4 (Major).'},
      {name:'Timid',sev:'Major',summary:'-2 to Fear checks and resisting Intimidation.'},
      {name:'Tongue-Tied',sev:'Major',summary:'-1 to Intimidation, Persuasion, and Taunt rolls.'},
      {name:'Ugly',sev:'Minor/Major',summary:'-1 (Minor) or -2 (Major) to Persuasion rolls.'},
      {name:'Vengeful',sev:'Minor/Major',summary:'Seeks payback for slights. As Major, will cause physical harm to get it.'},
      {name:'Vow',sev:'Minor/Major',summary:'Has pledged himself to some cause.'},
      {name:'Wanted',sev:'Minor/Major',summary:'Wanted by the authorities.'},
      {name:'Young',sev:'Minor/Major',summary:'Minor: 4 attribute points, 10 skill points, extra Benny per session. Major: 3 attribute points, 10 skill points, two extra Bennies per session.'}
    ],

    // ── ARCANE BACKGROUNDS ──
    arcaneBGs: [
      {name:'Gifted', skill:'Focus', linked:'spirit', startPP:15, startPowers:1, notes:'Innate ability'},
      {name:'Magic', skill:'Spellcasting', linked:'smarts', startPP:10, startPowers:3, notes:'Learned magic, gestures and incantations'},
      {name:'Miracles', skill:'Faith', linked:'spirit', startPP:10, startPowers:3, notes:'Divine power through faith and holy symbols'},
      {name:'Psionics', skill:'Psionics', linked:'smarts', startPP:10, startPowers:3, notes:'Mental powers, concentration'},
      {name:'Weird Science', skill:'Weird Science', linked:'smarts', startPP:15, startPowers:2, notes:'Devices and gizmos, can malfunction'}
    ],

    // ── POWERS ──
    powers: [
      {name:'Arcane Protection',rank:'N',pp:'1',range:'Smarts',dur:'5',summary:'Enemy casters subtract 2 (4 with a raise) when targeting this character; reduces damage a like amount.'},
      {name:'Banish',rank:'V',pp:'3',range:'Smarts',dur:'Instant',summary:'Opposed roll vs Spirit to banish entities to their native plane.'},
      {name:'Barrier',rank:'S',pp:'2',range:'Smarts',dur:'5',summary:'Creates 5 inch (10 yard) long, 1 inch (2 yard) tall wall with Hardness 10 (12 with a raise).'},
      {name:'Beast Friend',rank:'N',pp:'Special',range:'Smarts',dur:'10 min',summary:'Controls animals. Cost equals sum of their Size (minimum 1 per creature).'},
      {name:'Blast',rank:'S',pp:'3',range:'Smarts x2',dur:'Instant',summary:'2d6 damage in Medium Blast Template (3d6 with a raise).'},
      {name:'Blind',rank:'N',pp:'2',range:'Smarts',dur:'Instant',summary:'Inflicts -2 penalty to all actions requiring sight (-4 with a raise). Victim rolls Vigor each turn to shake off.'},
      {name:'Bolt',rank:'N',pp:'1',range:'Smarts x2',dur:'Instant',summary:'2d6 ranged attack (3d6 with a raise). No Range penalties but affected by Cover and Illumination.'},
      {name:'Boost/Lower Trait',rank:'N',pp:'3',range:'Smarts',dur:'5 / Instant',summary:'Boost increases a Trait one die type (two with raise) for 5 rounds. Lower decreases one die type (two with raise), Instant duration, victim rolls Spirit each turn to recover.'},
      {name:'Burrow',rank:'N',pp:'2',range:'Smarts',dur:'5',summary:'Target melds into earth, moves at half Pace (full with raise). May not run. Can surprise foes with Stealth vs Notice.'},
      {name:'Burst',rank:'N',pp:'2',range:'Cone',dur:'Instant',summary:'Cone Template from caster. 2d6 damage (3d6 with a raise).'},
      {name:'Confusion',rank:'N',pp:'1',range:'Smarts',dur:'Special',summary:'Targets in Medium Blast Template become Distracted or Vulnerable (both with a raise). Removed at end of victims\' next turn.'},
      {name:'Damage Field',rank:'S',pp:'4',range:'Smarts',dur:'5',summary:'Creates aura around recipient. All adjacent beings automatically take 2d4 damage at end of affected character\'s turn.'},
      {name:'Darksight',rank:'N',pp:'1',range:'Smarts',dur:'1 hour',summary:'Ignore up to 4 points of Illumination penalties (6 with a raise, can see in pitch darkness).'},
      {name:'Deflection',rank:'N',pp:'2',range:'Smarts',dur:'5',summary:'-2 to incoming ranged attacks (both ranged and melee with a raise).'},
      {name:'Detect/Conceal Arcana',rank:'N',pp:'2',range:'Smarts',dur:'Special',summary:'Detects magic for Duration 5, or conceals it for one hour.'},
      {name:'Disguise',rank:'S',pp:'2',range:'Smarts',dur:'10 min',summary:'Target looks like someone else.'},
      {name:'Dispel',rank:'N',pp:'1',range:'Smarts',dur:'Instant',summary:'Negates magical effects. Opposed arcane skill roll vs the original caster\'s.'},
      {name:'Divination',rank:'S',pp:'5',range:'Self',dur:'5 min',summary:'Caster asks questions of entities or higher powers.'},
      {name:'Drain Power Points',rank:'V',pp:'2',range:'Smarts',dur:'Instant',summary:'Drains d6 Power Points from enemy with successful opposed roll of arcane skills.'},
      {name:'Elemental Manipulation',rank:'N',pp:'1',range:'Smarts',dur:'5',summary:'Allows minor manipulation of basic elements (fire, water, earth, air).'},
      {name:'Empathy',rank:'N',pp:'1',range:'Smarts',dur:'5',summary:'Opposed roll vs Spirit to add +1 (+2 with raise) to social skills for the Duration.'},
      {name:'Entangle',rank:'N',pp:'2',range:'Smarts',dur:'Instant',summary:'Success Binds the target (must break free with Athletics or Strength at -2). Raise Entangles (Bound and Distracted).'},
      {name:'Environmental Protection',rank:'N',pp:'2',range:'Smarts',dur:'1 hour',summary:'Protects target from one hazardous environment (heat, cold, radiation, etc.).'},
      {name:'Farsight',rank:'S',pp:'2',range:'Smarts',dur:'5',summary:'See detail at great distance. Halves Range penalties with a raise.'},
      {name:'Fear',rank:'N',pp:'2',range:'Smarts',dur:'Instant',summary:'Causes a Fear check. With a raise, targets subtract 2 from the Fear check.'},
      {name:'Fly',rank:'V',pp:'3',range:'Smarts',dur:'5',summary:'Target flies at Pace 12 inches.'},
      {name:'Growth/Shrink',rank:'S',pp:'Special',range:'Smarts',dur:'5',summary:'Increases or decreases Size. Each level costs 2 PP (Growth) or 2 PP (Shrink).'},
      {name:'Havoc',rank:'N',pp:'2',range:'Smarts',dur:'Instant',summary:'Targets in Medium Blast Template or Cone are Distracted and may be hurled 2d6 inches.'},
      {name:'Healing',rank:'N',pp:'3',range:'Touch',dur:'Instant',summary:'Restores one Wound with success, two with a raise. Wounds must be less than one hour old.'},
      {name:'Illusion',rank:'N',pp:'3',range:'Smarts',dur:'5',summary:'Creates imaginary images. Opposed Smarts roll to see through them.'},
      {name:'Intangibility',rank:'V',pp:'5',range:'Smarts',dur:'5',summary:'Target becomes incorporeal. Cannot affect or be affected by the physical world.'},
      {name:'Invisibility',rank:'S',pp:'5',range:'Smarts',dur:'5',summary:'Target is transparent. -4 to actions requiring sight against them (-6 with a raise).'},
      {name:'Light/Darkness',rank:'N',pp:'2',range:'Smarts',dur:'10 min',summary:'Light creates bright illumination in a Large Blast Template. Darkness makes area Dark (Pitch Darkness with raise).'},
      {name:'Mind Link',rank:'N',pp:'1',range:'Smarts',dur:'30 min',summary:'Telepathic connection between two willing individuals. Range one mile (five with raise).'},
      {name:'Mind Reading',rank:'N',pp:'2',range:'Smarts',dur:'Instant',summary:'Opposed roll vs target\'s Smarts. Gain one truthful answer. Target aware unless raise.'},
      {name:'Mind Wipe',rank:'V',pp:'3',range:'Smarts',dur:'Instant',summary:'Removes and alters memories. Opposed arcane skill vs Smarts.'},
      {name:'Object Reading',rank:'S',pp:'2',range:'Touch',dur:'Special',summary:'Reveals vague information about an object\'s history (more detail with a raise).'},
      {name:'Protection',rank:'N',pp:'1',range:'Smarts',dur:'5',summary:'Grants +2 Armor (Toughness with a raise).'},
      {name:'Puppet',rank:'V',pp:'3',range:'Smarts',dur:'5',summary:'Opposed roll vs Spirit to control target\'s actions.'},
      {name:'Relief',rank:'N',pp:'1',range:'Smarts',dur:'Instant',summary:'Removes one level of Fatigue, or one negative condition (Shaken, Distracted, Vulnerable, Stunned).'},
      {name:'Resurrection',rank:'H',pp:'30',range:'Touch',dur:'Instant',summary:'Brings the dead back to life.'},
      {name:'Shape Change',rank:'N',pp:'Special',range:'Self',dur:'5',summary:'Caster takes on the form of various beings. Cost depends on Size.'},
      {name:'Sloth/Speed',rank:'S',pp:'2',range:'Smarts',dur:'Instant / 5',summary:'Sloth reduces target\'s Pace and running die (Instant, resisted by Spirit). Speed doubles Pace and running die for 5 rounds.'},
      {name:'Slumber',rank:'S',pp:'2',range:'Smarts',dur:'1 hour',summary:'Target falls asleep. Resisted by Spirit.'},
      {name:'Smite',rank:'N',pp:'2',range:'Smarts',dur:'5',summary:'Increases a weapon\'s damage by +2 (+4 with a raise).'},
      {name:'Sound/Silence',rank:'N',pp:'1',range:'Smarts x5 / Smarts',dur:'Instant / 5',summary:'Sound creates noise at a distant point. Silence mutes sound in a Small Blast Template.'},
      {name:'Speak Language',rank:'N',pp:'1',range:'Smarts',dur:'10 min',summary:'Speak, read, and write a language. Raise grants slang and dialect fluency.'},
      {name:'Stun',rank:'N',pp:'2',range:'Smarts',dur:'Instant',summary:'Target must make Vigor roll (-2 with raise) or be Stunned.'},
      {name:'Summon Ally',rank:'N',pp:'Special',range:'Smarts',dur:'5',summary:'Conjures an ally. Novice=Attendant(1PP), Seasoned=Bodyguard(3PP), Veteran=Sentinel(5PP), Heroic=Mirror Self(7PP).'},
      {name:'Telekinesis',rank:'S',pp:'5',range:'Smarts x2',dur:'5',summary:'Moves items with Strength d10 (d12 with raise). Can bash (Str+d6), move, or manipulate objects.'},
      {name:'Teleport',rank:'S',pp:'2',range:'Smarts',dur:'Instant',summary:'Teleport up to 12 inches (24 yards), double with raise. -2 to unseen locations. No free attack from adjacent foes.'},
      {name:'Wall Walker',rank:'N',pp:'2',range:'Smarts',dur:'5',summary:'Walk on walls at half Pace (full Pace with raise). +4 to Athletics to climb or hang on.'},
      {name:'Warrior\'s Gift',rank:'S',pp:'4',range:'Smarts',dur:'5',summary:'Grant target a single Combat Edge. Caster must be same Rank or higher as the Edge. Raise grants Improved version.'},
      {name:'Zombie',rank:'V',pp:'3',range:'Smarts',dur:'1 hour',summary:'Raises and controls the undead. Cost 3PP for human-sized. Follows simple commands.'}
    ],

    // ── GEAR ──
    gear: {
      melee: [
        {name:'Axe, Hand',dmg:'Str+d6',minStr:'d6',cost:100,wt:2,notes:''},
        {name:'Axe, Battle',dmg:'Str+d8',minStr:'d8',cost:300,wt:4,notes:''},
        {name:'Axe, Great',dmg:'Str+d10',minStr:'d10',cost:400,wt:7,notes:'AP 2, Parry -1, two hands'},
        {name:'Club, Light',dmg:'Str+d4',minStr:'d4',cost:25,wt:2,notes:''},
        {name:'Club, Heavy',dmg:'Str+d6',minStr:'d6',cost:50,wt:5,notes:''},
        {name:'Dagger/Knife',dmg:'Str+d4',minStr:'d4',cost:25,wt:1,notes:''},
        {name:'Flail',dmg:'Str+d6',minStr:'d6',cost:200,wt:3,notes:'Ignores Shield bonus'},
        {name:'Halberd',dmg:'Str+d8',minStr:'d8',cost:250,wt:6,notes:'Reach 1, two hands'},
        {name:'Katana',dmg:'Str+d6+1',minStr:'d6',cost:1000,wt:3,notes:'Two hands'},
        {name:'Lance',dmg:'Str+d8',minStr:'d8',cost:300,wt:6,notes:'AP 2 when charging, Reach 2, mounted combat only'},
        {name:'Mace',dmg:'Str+d6',minStr:'d6',cost:100,wt:4,notes:''},
        {name:'Maul',dmg:'Str+d10',minStr:'d10',cost:400,wt:10,notes:'Two hands, +2 damage to break objects'},
        {name:'Pike',dmg:'Str+d8',minStr:'d8',cost:400,wt:18,notes:'Reach 2, two hands'},
        {name:'Rapier',dmg:'Str+d4',minStr:'d4',cost:150,wt:2,notes:'Parry +1'},
        {name:'Spear',dmg:'Str+d6',minStr:'d6',cost:100,wt:3,notes:'Reach 1, Parry +1 if used two-handed'},
        {name:'Staff',dmg:'Str+d4',minStr:'d4',cost:10,wt:4,notes:'Parry +1, Reach 1, two hands'},
        {name:'Sword, Great',dmg:'Str+d10',minStr:'d10',cost:400,wt:6,notes:'Two hands'},
        {name:'Sword, Long',dmg:'Str+d8',minStr:'d8',cost:300,wt:3,notes:'Includes scimitars'},
        {name:'Sword, Short',dmg:'Str+d6',minStr:'d6',cost:100,wt:2,notes:'Includes cavalry sabers'},
        {name:'Warhammer',dmg:'Str+d6',minStr:'d6',cost:250,wt:2,notes:'AP 1'}
      ],
      ranged: [
        {name:'Axe, Throwing',dmg:'Str+d6',range:'3/6/12',ap:0,rof:1,minStr:'d6',cost:100,wt:3,notes:''},
        {name:'Bow',dmg:'2d6',range:'12/24/48',ap:0,rof:1,minStr:'d6',cost:250,wt:3,notes:''},
        {name:'Crossbow',dmg:'2d6',range:'10/20/40',ap:2,rof:1,minStr:'d6',cost:250,wt:5,notes:'Hand-drawn'},
        {name:'Crossbow, Heavy',dmg:'2d8',range:'15/30/60',ap:2,rof:1,minStr:'d6',cost:400,wt:8,notes:'Windlass to load, Reload 2'},
        {name:'Dagger/Knife (thrown)',dmg:'Str+d4',range:'3/6/12',ap:0,rof:1,minStr:'d4',cost:25,wt:1,notes:''},
        {name:'Net (Weighted)',dmg:'',range:'3/6/12',ap:0,rof:1,minStr:'d4',cost:50,wt:8,notes:'Restrain only, no damage. See Entangle rules.'},
        {name:'Sling',dmg:'Str+d4',range:'4/8/16',ap:0,rof:1,minStr:'d4',cost:10,wt:1,notes:''},
        {name:'Spear (thrown)',dmg:'Str+d6',range:'3/6/12',ap:0,rof:1,minStr:'d6',cost:100,wt:3,notes:''}
      ],
      armor: [
        {name:'Jacket (torso, arms)',armor:1,minStr:'d4',cost:20,wt:5,notes:''},
        {name:'Robes (torso, arms, legs)',armor:1,minStr:'d4',cost:30,wt:8,notes:''},
        {name:'Leggings (legs)',armor:1,minStr:'d4',cost:20,wt:5,notes:''},
        {name:'Cap (head)',armor:1,minStr:'d4',cost:5,wt:1,notes:''},
        {name:'Jacket (torso, arms)',armor:2,minStr:'d6',cost:80,wt:8,notes:''},
        {name:'Leggings (legs)',armor:2,minStr:'d6',cost:40,wt:7,notes:''},
        {name:'Cap (head)',armor:2,minStr:'d6',cost:20,wt:1,notes:''},
        {name:'Shirt (torso, arms)',armor:3,minStr:'d8',cost:300,wt:25,notes:''},
        {name:'Leggings (legs)',armor:3,minStr:'d8',cost:150,wt:10,notes:''},
        {name:'Chain Hood/Helm (head)',armor:3,minStr:'d8',cost:25,wt:4,notes:''},
        {name:'Corselet (torso)',armor:4,minStr:'d10',cost:500,wt:30,notes:''},
        {name:'Vambraces (arms, pair)',armor:4,minStr:'d10',cost:200,wt:10,notes:''},
        {name:'Greaves (legs, pair)',armor:4,minStr:'d10',cost:200,wt:10,notes:''},
        {name:'Heavy Helm (head)',armor:4,minStr:'d10',cost:100,wt:4,notes:''},
        {name:'Heavy Helm, Enclosed (head)',armor:4,minStr:'d10',cost:200,wt:8,notes:'-1 to vision-based Notice rolls'},
        {name:'Plate Barding (horse)',armor:4,minStr:'d10',cost:1500,wt:50,notes:''}
      ],
      shields: [
        {name:'Shield, Small',parry:1,cover:0,minStr:'d4',cost:50,wt:4,notes:'Can bash for Str+d4'},
        {name:'Shield, Medium',parry:2,cover:2,minStr:'d6',cost:100,wt:8,notes:'Can bash for Str+d4'},
        {name:'Shield, Large',parry:3,cover:4,minStr:'d8',cost:200,wt:12,notes:'Can bash for Str+d4'}
      ],
      general: [
        {name:'Backpack',cost:50,wt:2},
        {name:'Bedroll',cost:25,wt:4},
        {name:'Blanket',cost:10,wt:4},
        {name:'Candle',cost:1,wt:1},
        {name:'Canteen/Waterskin',cost:5,wt:1},
        {name:'Crowbar',cost:10,wt:2},
        {name:'First Aid Kit',cost:10,wt:1},
        {name:'Flask (ceramic)',cost:5,wt:1},
        {name:'Flint and Steel',cost:3,wt:1},
        {name:'Grappling Hook',cost:100,wt:2},
        {name:'Hammer',cost:10,wt:1},
        {name:'Handcuffs/Manacles',cost:15,wt:2},
        {name:'Lantern',cost:25,wt:3},
        {name:'Lockpicks',cost:200,wt:1},
        {name:'Oil (one pint)',cost:2,wt:1},
        {name:'Quiver',cost:25,wt:2},
        {name:'Rope, hemp (20 yds)',cost:10,wt:15},
        {name:'Shovel',cost:5,wt:5},
        {name:'Soap',cost:1,wt:0.2},
        {name:'Tool Kit',cost:200,wt:5},
        {name:'Torch',cost:5,wt:1},
        {name:'Whetstone',cost:5,wt:1},
        {name:'Boots, Hiking',cost:100,wt:2},
        {name:'Clothing, Casual',cost:20,wt:2},
        {name:'Clothing, Formal',cost:200,wt:3},
        {name:'Winter Gear (cloak/parka)',cost:200,wt:3},
        {name:'Trail Rations',cost:10,wt:5},
        {name:'Good Meal',cost:15,wt:0},
        {name:'Horse',cost:300,wt:0},
        {name:'War Horse',cost:750,wt:0},
        {name:'Saddle',cost:10,wt:10},
        {name:'Elaborate Saddle',cost:50,wt:10}
      ]
    }
  });
})();